Traceback (most recent call last):
  File "/home/oriol_colome_font_epidemicsound_/Master-Thesis-1/train.py", line 52, in <module>
    trainer = pl.Trainer(devices='1', accelerator='gpu', max_epochs=10, logger=wandb_logger)
  File "/opt/conda/envs/master_thesis/lib/python3.10/site-packages/pytorch_lightning/utilities/argparse.py", line 69, in insert_env_defaults
    return fn(self, **kwargs)
  File "/opt/conda/envs/master_thesis/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 393, in __init__
    self._accelerator_connector = _AcceleratorConnector(
  File "/opt/conda/envs/master_thesis/lib/python3.10/site-packages/pytorch_lightning/trainer/connectors/accelerator_connector.py", line 154, in __init__
    self._accelerator_flag = self._choose_gpu_accelerator_backend()
  File "/opt/conda/envs/master_thesis/lib/python3.10/site-packages/pytorch_lightning/trainer/connectors/accelerator_connector.py", line 368, in _choose_gpu_accelerator_backend
    raise MisconfigurationException("No supported gpu backend found!")
lightning_fabric.utilities.exceptions.MisconfigurationException: No supported gpu backend found!